version: "3"

services:
  # GraphQL API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - catalog-service
      - order-service
    environment:
      - ACCOUNT_SERVICE_URL=account-service:50051
      - CATALOG_SERVICE_URL=catalog-service:50052
      - ORDER_SERVICE_URL=order-service:50053

  # Account Service
  account-service:
    build:
      context: ./account
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres-account

  # Catalog Service
  catalog-service:
    build:
      context: ./catalog
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - elasticsearch

  # Order Service
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    depends_on:
      - postgres-order
      - catalog-service
      - account-service

  # PostgreSQL for Account Service
  postgres-account:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-account-data:/var/lib/postgresql/data

  # PostgreSQL for Order Service
  postgres-order:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  # Elasticsearch for Catalog Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  # Frontend React App
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api-gateway
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8080/query

volumes:
  postgres-account-data:
  postgres-order-data:
  elasticsearch-data:
